### ISSUE TITLE
Wont follow cursor

### ISSUE THREAD

**Issue by juancarlospaco** [andykitchen/swcursor#1]
It creates an overlay window with an (large) image that do **Not** follows the cursor around.

![swcursor](https://user-images.githubusercontent.com/1189414/53295958-25a32c80-37e5-11e9-8b51-850ae9fdc8e2.png)

More Info:
```
$ uname -a ; lsb_release -a
Linux x 4.20.10-arch1-1-ARCH #1 SMP PREEMPT Fri Feb 15 17:49:06 UTC 2019 x86_64 GNU/Linux
LSB Version:    1.4
Distributor ID: Antergos
Description:    Antergos Linux
Release:        rolling
Codename:       n/a
```

Desktop is vanilla KDE5 (Qt5) default configs.
It creates an `Xwindow` on the list of windows on the bottom taskbar.
Inside the window it does follow mouse cursor but it leaves a trail of the image.
I can not drag around the window, it just like fixed at (0, 0).
Hardware is just a generic vanilla mouse.

**Comment by andykitchen** [comment]
Ah, that's annoying, thanks for trying it out and reporting back.

Unfortunately I don't have a good way to debug this as I don't have a KDE machine to reproduce with.

   * Are you running with a compositing window manager? Do other transparent windows work?
   * Do you have multiple screens? I've never tested this with multiple screens, my suspicion is that it would not work well. Could you please try it with only one screen attached?

I think there might really be 2 problems here. The graphical glitches and the inability to track the mouse correctly. The first problem may be caused by the absence of a compositing window manger, or some weird interaction with GTK/GDK and the KDE window manager (plasma?) I currently redraw on the "draw" GTK/GDK event, but I've seen other people redraw on the X "expose" event, that may be necessary...

In regard to the mouse tracking problems, it probably means that XQueryPointer is returning false for whatever reason, I think false is returned if we are querying the wrong screen, but I don't really know the other failure modes, unfortunately Xlib doesn't have great documentation that I could find.

When I get some spare time this week, I'll try adding some more defensive code with better error reporting and push it to a branch for you to try.

AK

**Comment by juancarlospaco** [comment]
> Are you running with a compositing window manager? 

Yes, KDE by default runs a builtin compositing window manager if it detect OpenGL,
I know it also runs without OpenGL (without any effects) I dont know how they do it tho.
But I think the problem is different, because it creates a XWindow on the Taskbar, and it should not.

> Do other transparent windows work?

Yes.

> Do you have multiple screens? 

No. 1 Screen.

> Could you please try it with only one screen attached?

Ive never connected a second screen on this PC.


Inside the tiny square it does track the mouse correctly, but leaves a trail,
but it wont follow the mouse across the whole screen, only inside the tiny rectangle at (0, 0),
it feels like a transparent window without borders, with an entry on the window list on taskbar,
but it wont track the mouse pass itself.
The trail is only from Left to Right, from Right to Left it works Ok with no trail.

From window manager I forced the tiny window to be fullscreen and it works, with clicks and all, 
but leaves trail from Left to Right, and creates an entry on window list, 
I can force the window manager to skip the window from the window list but its kinda hacky,
but I find no way to skip the trail that gets too annoying for actual use, I was planning to use it for Twitch.tv streaming.

If you can comment out the code, argument types, return types, make a public API,
I would like to make a Nim lang wrapper for it too, so it can be used on other projects and programming languages.

**Comment by juancarlospaco** [comment]
## Workaround for KDE


![swcursor0](https://user-images.githubusercontent.com/1189414/53310638-6b670000-388c-11e9-8ef4-2da226dac5c4.png)


![swcursor1](https://user-images.githubusercontent.com/1189414/53310639-70c44a80-388c-11e9-9de1-fdedd3ffd879.png)


![swcursor2](https://user-images.githubusercontent.com/1189414/53310642-7326a480-388c-11e9-9903-1840c5a1f121.png)


![swcursor3](https://user-images.githubusercontent.com/1189414/53310644-74f06800-388c-11e9-9505-42d16dfdcce4.png)

- Fixes all problems, but still leaves a Trail only from Left to Right of screen.

**Comment by andykitchen** [comment]
Oh wow, cool, you're my first user for this project. Let's figure out how to get it working for you!

Here's what I did after I saw you post but before your reply: A big cleanup, which turned into a huge refactor. With the hope that any random jankyness goes away. All my X11 hacks are now much better integrated into the GTK/GDK window lifecycle. So it's worth pulling to get the new hotness.

Your reply has given me some ideas, but let my know what you think is most promising:

1. A fullscreen overlay mode. Create a fullscreen transparent window and just change where the
image is drawn to follow the mouse, instead of trying to constantly move a window.
2. Adding a "margin" by making the cursor window somewhat larger than the cursor image. This might fix ghosting / trails caused by partial updates not lining up.
3. Trying to draw to the XComposite overlay window https://linux.die.net/man/3/xcomposite I'm not sure how well supported / compatible this feature is in the wild, my very limited experiments didn't work on my computer.

**Comment by juancarlospaco** [comment]
It Works Ok :grey_exclamation: No trail and super smooth :grey_exclamation: The Window Manager Hack is no required.
Even on top of OpenGL Windows and with other PNG :grey_exclamation:  :slightly_smiling_face: :+1: 

This is Fixed, I will Close the issue.
If you can comment out the code as I said, but is working anyways.

**Comment by andykitchen** [comment]
What's your twitch stream BTW?

**Comment by juancarlospaco** [comment]
Twitch Stream: https://www.twitch.tv/juancarlospaco
The programming language I use (compiles to C): https://nim-lang.org/features.html
This is how it interoperates with C: https://github.com/juancarlospaco/nim-presentation-slides/blob/master/ejemplos/basico/c/ejemplo.nim :arrow_right: https://github.com/juancarlospaco/nim-presentation-slides/blob/master/ejemplos/basico/c/suma.c
https://github.com/juancarlospaco/nim-presentation-slides/blob/master/ejemplos/basico/c/saluda.nim :arrow_right: https://github.com/juancarlospaco/nim-presentation-slides/blob/master/ejemplos/basico/c/simple.c
:smile:
